services:
  - type: web
    name: Kinobum
    runtime: docker
    dockerfilePath: bot/Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: ADMIN_IDS
        value: 6998664132
      - key: BOT_TOKEN
        sync: false
      - key: BACKUP_CHANNEL_ID
        sync: false
