services:
  - type: web
    name: Kinobum
    runtime: python
    rootDir: bot
    buildCommand: pip install --upgrade pip setuptools wheel && pip install --prefer-binary -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PORT
        value: 10000
      - key: ADMIN_IDS
        value: 6998664132
      - key: BOT_TOKEN
        sync: false
      - key: BACKUP_CHANNEL_ID
        sync: false
